name:                aoc2018
version:             0.1.0.0
github:              "jw1200/aoc2018"
license:             BSD3
author:              "Joe Watson"
maintainer:          "joe_watson@mail.com"
copyright:           "2018 Joe Watson"
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2018#readme>

source-dirs: src

extra-source-files:
- README.md

# We include all dependencies here so stack will find them when editting
dependencies:
- base >= 4.7 && < 5
- containers
- array
- attoparsec
- bytestring
- doctest

executables:
  day01:
    main: day01.hs
    ghc-options: -main-is Day01
  day02:
    main: day02.hs
    ghc-options: -main-is Day02
  day03:
    main: day03.hs
    ghc-options: -main-is Day03
  day04:
    main: day04.hs
    ghc-options: -main-is Day04
  day05:
    main: day05.hs
    ghc-options: -main-is Day05
  day06:
    main: day06.hs
    ghc-options: -main-is Day06
  day07:
    main: day07.hs
    ghc-options: -main-is Day07
  day08:
    main: day08.hs
    ghc-options: -main-is Day08
  day09:
    main: day09.hs
    ghc-options: -main-is Day09

tests:
  doctest:
    source-dirs:        test
    main:               doctest.hs
