name:                aoc2018
version:             0.1.0.0
github:              "jw1200/aoc2018"
license:             BSD3
author:              "Joe Watson"
maintainer:          "joe_watson@mail.com"
copyright:           "2018 Joe Watson"
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2018#readme>

source-dirs: src

extra-source-files:
- README.md

# We include all dependencies here so stack will find them when editting
dependencies:
  - base >= 4.7 && < 5
  - containers
  - array
  - attoparsec
  - bytestring
  - doctest
#- monad-loop
#- mtl

executables:
  # day01:
  #   main: day01.hs
  #   ghc-options: -main-is Day01
  # day02:
  #   main: day02.hs
  #   ghc-options: -main-is Day02
  # day03:
  #   main: day03.hs
  #   ghc-options: -main-is Day03
  # day04:
  #   main: day04.hs
  #   ghc-options: -main-is Day04
  # day05:
  #   main: day05.hs
  #   ghc-options: -main-is Day05
  # day06:
  #   main: day06.hs
  #   ghc-options: -main-is Day06
  # day07:
  #   main: day07.hs
  #   ghc-options: -main-is Day07
  # day08:
  #   main: day08.hs
  #   ghc-options: -main-is Day08
  # day09:
  #   main: day09.hs
  #   ghc-options: -main-is Day09
  # day10:
  #   main: day10.hs
  #   ghc-options: -main-is Day10
  # day11:
  #   main: day11.hs
  #   ghc-options: -main-is Day11
  # day12:
  #   main: day12.hs
  #   ghc-options: -main-is Day12
  # day13:
  #   main: day13.hs
  #   ghc-options: -main-is Day13
  #day14:
  #  main: day14.hs
  #  ghc-options: -main-is Day14
  # day15:
  #   main: day15.hs
  #   ghc-options: -main-is Day15
  #day16:
  #  main: day16.hs
  #  ghc-options: -main-is Day16
  #day18:
  #   main: day18.hs
  #   ghc-options: -main-is Day18
  #day19:
  #  main: day19.hs
  #  ghc-options: -main-is Day19
  # day20:
  #   main: day20.hs
  #   ghc-options: -main-is Day20
  # day22:
  #  main: day22.hs
  #  ghc-options: -main-is Day22
  #day23:
  #  main: day23.hs
  #  ghc-options: -main-is Day23
  day24:
    main: day24.hs
    ghc-options: -main-is Day24

tests:
  doctest:
    source-dirs:        test
    main:               doctest.hs
