name:                aoc2018
version:             0.1.0.0
github:              "jw1200/aoc2018"
license:             BSD3
author:              "Joe Watson"
maintainer:          "joe_watson@mail.com"
copyright:           "2018 Joe Watson"
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2018#readme>

source-dirs: src

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers

executables:
  day01:
    main: day01.hs
    ghc-options: -main-is Day01
  day02:
    main: day02.hs
    ghc-options: -main-is Day02
  day03:
    main: day03.hs
    ghc-options: -main-is Day03

tests:
  doctests:
    source-dirs:        test
    main:               doctest-driver.hs
    dependencies:
      - doctest
      - doctest-discover
